import { resolve } from "node:path";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { descendants, inferTokens, type MirrorNode } from "@figma-mirror/shared";
import { z } from "zod";
import { api, baseUrl, binary } from "./client";

type Project = { id: string; name: string; source: string };
type Snapshot = { id: string; projectId: string; version: number; documentName: string; pageName: string; rootNodeId: string; rootNodeName: string; nodeCount: number; metadata: Record<string, unknown>; createdAt: string };
type DbNode = { figmaNodeId: string; parentNodeId: string | null; name: string; type: string; path: string; depth: number; data: MirrorNode };
type Asset = { externalId: string; nodeId: string; kind: string; mimeType: string; hash: string; path: string; metadata: Record<string, unknown> };
const text = (value: unknown) => ({ content: [{ type: "text" as const, text: JSON.stringify(value, null, 2) }] });
const nodes = async (snapshotId: string) => (await api<DbNode[]>(`/snapshots/${snapshotId}/nodes`)).map((row) => row.data);
const compact = (node: MirrorNode) => ({ id: node.id, name: node.name, type: node.type, path: node.path, dimensions: node.width !== undefined ? `${node.width}×${node.height}` : undefined, layout: { mode: node.data.layoutMode, wrap: node.data.layoutWrap, padding: [node.data.paddingTop, node.data.paddingRight, node.data.paddingBottom, node.data.paddingLeft], gap: node.data.itemSpacing, align: [node.data.primaryAxisAlignItems, node.data.counterAxisAlignItems] }, text: node.data.characters, typography: node.type === "TEXT" ? { font: node.data.fontName, size: node.data.fontSize, weight: node.data.fontWeight, lineHeight: node.data.lineHeight, letterSpacing: node.data.letterSpacing, runs: node.data.runs } : undefined, fills: node.data.fills, effects: node.data.effects, component: node.data.componentName ? { name: node.data.componentName, properties: node.data.componentProperties, variants: node.data.variantProperties } : undefined, assetRefs: node.data.imageHash });
function createServer() {
  const server = new McpServer({ name: "figma-mirror", version: "0.1.0" }, { instructions: "Figma Mirror contains immutable local snapshots. Start with list_projects/get_latest_snapshot, then inspect_design for an implementation-ready visual and structural package. Prefer bounded get_node/get_frame calls over fetching entire trees." });
  server.registerTool("list_projects", { description: "List locally mirrored Figma projects." }, async () => text(await api<Project[]>("/projects")));
  server.registerTool("list_snapshots", { description: "List READY immutable snapshot versions.", inputSchema: { projectId: z.string().optional() } }, async ({ projectId }) => text(await api<Snapshot[]>(`/snapshots${projectId ? `?projectId=${encodeURIComponent(projectId)}` : ""}`)));
  server.registerTool("get_latest_snapshot", { description: "Get the latest READY snapshot for a project.", inputSchema: { projectId: z.string() } }, async ({ projectId }) => text(await api<Snapshot>(`/projects/${projectId}/latest`)));
  server.registerTool("list_pages", { description: "List pages represented by READY snapshots.", inputSchema: { projectId: z.string().optional() } }, async ({ projectId }) => { const snapshots = await api<Snapshot[]>(`/snapshots${projectId ? `?projectId=${encodeURIComponent(projectId)}` : ""}`); return text([...new Map(snapshots.map((s) => [`${s.projectId}:${s.pageName}`, { projectId: s.projectId, pageName: s.pageName, latestSnapshotId: s.id }])).values()]); });
  server.registerTool("list_frames", { description: "List top-level frames and components without returning their trees.", inputSchema: { snapshotId: z.string(), page: z.string().optional() } }, async ({ snapshotId, page }) => { const snapshot = await api<Snapshot>(`/snapshots/${snapshotId}`); const all = await nodes(snapshotId); return text(page && page !== snapshot.pageName ? [] : all.filter((n) => n.depth <= 1 && ["FRAME", "COMPONENT", "COMPONENT_SET", "SECTION"].includes(n.type)).map((n) => ({ id: n.id, name: n.name, type: n.type, width: n.width, height: n.height, childCount: n.children.length, path: n.path }))); });
  server.registerTool("search_nodes", { description: "Search node names, visible text, paths, types, and component names.", inputSchema: { snapshotId: z.string(), query: z.string(), types: z.array(z.string()).optional(), limit: z.number().int().min(1).max(100).default(20) } }, async ({ snapshotId, query, types, limit }) => text(await api<DbNode[]>(`/snapshots/${snapshotId}/nodes?q=${encodeURIComponent(query)}&limit=${limit}${types?.length ? `&types=${encodeURIComponent(types.join(","))}` : ""}`)));
  server.registerTool("get_node", { description: "Get a node and a bounded number of descendant levels (default 1).", inputSchema: { snapshotId: z.string(), nodeId: z.string(), depth: z.number().int().min(0).max(10).default(1) } }, async ({ snapshotId, nodeId, depth }) => text(descendants(await nodes(snapshotId), nodeId, depth)));
  server.registerTool("get_frame", { description: "Get an AI-friendly bounded frame representation and screenshot reference.", inputSchema: { snapshotId: z.string(), frameId: z.string(), depth: z.number().int().min(0).max(10).default(2), includeScreenshot: z.boolean().default(true) } }, async ({ snapshotId, frameId, depth, includeScreenshot }) => { const all = await nodes(snapshotId); const tree = descendants(all, frameId, depth); return text({ frame: compact(tree[0]!), children: tree.slice(1).map(compact), screenshot: includeScreenshot ? `${baseUrl}/snapshots/${snapshotId}/screenshots/${encodeURIComponent(frameId)}` : undefined }); });
  server.registerTool("get_design_tokens", { description: "Return declared Figma variables separately from inferred frequent visual values.", inputSchema: { snapshotId: z.string() } }, async ({ snapshotId }) => { const snapshot = await api<Snapshot>(`/snapshots/${snapshotId}`); const all = await nodes(snapshotId); return text({ declaredTokens: { collections: snapshot.metadata.collections ?? [], variables: snapshot.metadata.variables ?? [] }, inferredTokens: inferTokens(all) }); });
  server.registerTool("get_component", { description: "Find a component by exact id or case-insensitive name and return its bounded tree.", inputSchema: { snapshotId: z.string(), componentNameOrId: z.string() } }, async ({ snapshotId, componentNameOrId }) => { const all = await nodes(snapshotId); const target = all.find((n) => n.id === componentNameOrId) ?? all.find((n) => ["COMPONENT", "COMPONENT_SET", "INSTANCE"].includes(n.type) && n.name.toLowerCase() === componentNameOrId.toLowerCase()); if (!target) throw new Error("Component not found"); return text(descendants(all, target.id, 2).map(compact)); });
  server.registerTool("get_asset", { description: "Get asset metadata and local path; inline image-capable formats when supported.", inputSchema: { snapshotId: z.string(), assetId: z.string() } }, async ({ snapshotId, assetId }) => { const asset = await api<Asset>(`/snapshots/${snapshotId}/assets/${encodeURIComponent(assetId)}`); const absolutePath = resolve(process.env.DATA_DIR ?? "./data", asset.path); return text({ ...asset, absolutePath }); });
  server.registerTool("get_screenshot", { description: "Return the original Figma screenshot as native MCP image content plus a safe absolute local path.", inputSchema: { snapshotId: z.string(), frameId: z.string() } }, async ({ snapshotId, frameId }) => { const assets = await api<Asset[]>(`/snapshots/${snapshotId}/assets`); const asset = assets.find((item) => item.kind === "SCREENSHOT" && item.nodeId === frameId); if (!asset) throw new Error("Screenshot not found"); const image = await binary(`/snapshots/${snapshotId}/screenshots/${encodeURIComponent(frameId)}`); return { content: [{ type: "text" as const, text: JSON.stringify({ frameId, absolutePath: resolve(process.env.DATA_DIR ?? "./data", asset.path), hash: asset.hash }) }, { type: "image" as const, data: Buffer.from(image.bytes).toString("base64"), mimeType: image.mimeType }] }; });
  server.registerTool("inspect_design", { description: "Primary tool: return the screenshot and compact implementation package for a node id, frame name, or component name.", inputSchema: { snapshotId: z.string(), target: z.string() } }, async ({ snapshotId, target }) => { const snapshot = await api<Snapshot>(`/snapshots/${snapshotId}`); const all = await nodes(snapshotId); const root = all.find((n) => n.id === target) ?? all.find((n) => n.name.toLowerCase() === target.toLowerCase()) ?? all.find((n) => n.path.toLowerCase().endsWith(target.toLowerCase())); if (!root) throw new Error(`Target '${target}' not found`); const subtree = descendants(all, root.id, 3); const assetRows = await api<Asset[]>(`/snapshots/${snapshotId}/assets`); const screenshot = assetRows.find((a) => a.kind === "SCREENSHOT" && a.nodeId === root.id); const payload = { target: root.path, viewport: `${root.width} × ${root.height}`, snapshot: { id: snapshot.id, version: snapshot.version, page: snapshot.pageName }, structure: subtree.map(compact), typography: subtree.filter((n) => n.type === "TEXT").map(compact), components: subtree.filter((n) => ["COMPONENT", "COMPONENT_SET", "INSTANCE"].includes(n.type)).map(compact), assets: assetRows.filter((a) => subtree.some((n) => n.id === a.nodeId)), tokens: { declared: { variables: snapshot.metadata.variables ?? [], collections: snapshot.metadata.collections ?? [] }, inferred: inferTokens(subtree) } }; const content: Array<{ type: "text"; text: string } | { type: "image"; data: string; mimeType: string }> = [{ type: "text", text: JSON.stringify(payload, null, 2) }]; if (screenshot) { const image = await binary(`/snapshots/${snapshotId}/screenshots/${encodeURIComponent(root.id)}`); content.unshift({ type: "image", data: Buffer.from(image.bytes).toString("base64"), mimeType: image.mimeType }); } return { content }; });
  return server;
}

const server = createServer(); await server.connect(new StdioServerTransport()); console.error("figma-mirror MCP ready on stdio");
